version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building the Petclinic Application
    - mvn clean install -DskipTests=true
artifacts:
  files:
  - target/spring-petclinic.jar
  discard-paths: yes